FROM public.ecr.aws/lambda/nodejs:18

# Copy package.json files and install dependencies
COPY package*.json ${LAMBDA_TASK_ROOT}/
RUN npm install --production

# Copy application code
COPY . ${LAMBDA_TASK_ROOT}/

# Set the handler
CMD [ "main.handler" ]