service:  izole-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1 # Change to your preferred region
  memorySize: 512
  timeout: 30

functions:
  api:
    image: ${env:ECR_IMAGE_URI}
    events:
      - httpApi: '*'
