service: izole-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1  # Change to your preferred region
  memorySize: 512
  timeout: 30
  environment:
    MONGO_URI: ${env:MONGO_URI}
    SECRET_KEY: ${env:SECRET_KEY}
    AWS_REGION: ${env:AWS_REGION}
    SCHEDULER_ROLE_ARN: ${env:SCHEDULER_ROLE_ARN}
    LAMBDA_ARN: ${env:LAMBDA_ARN}

functions:
  api:
    name: 'izole-api'
    handler: main.handler  # Main handler for both API Gateway and EventBridge
    image: ${env:ECR_IMAGE_URI}
    events:
      - httpApi: '*'  # API Gateway event

  # No need to define a separate function for EventBridge since it's routed dynamically in the handler

resources:
  Resources:
    SchedulerRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-scheduler-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: scheduler.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SchedulerInvokeLambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage}-api

custom:
  dotenv:
    path: .env
    include:
      - MONGO_URI
      - SECRET_KEY