service: izole-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1  # Change to your preferred region
  memorySize: 512
  timeout: 30
  environment:
    MONGO_URI: ${env:MONGO_URI}
    SECRET_KEY: ${env:SECRET_KEY}
    
package:
  patterns:
    - '!node_modules/.cache/**'
    - '!.git/**'
    - '!.github/**'
    - '!tests/**'
    - 'node_modules/**' # Include node_modules
    - 'package-lock.json'

functions:
  api:
    name: 'izole-api'
    handler: main.handler
    events:
      - http:
          path: /{proxy+}
          method: any
custom:
  dotenv:
    path: .env
    include:
      - MONGO_URI
      - SECRET_KEY
   