service: izole-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1  # Change to your preferred region
  memorySize: 512
  timeout: 30
  environment:
    MONGO_URI: ${env:MONGO_URI}
    SECRET_KEY: ${env:SECRET_KEY}
    
# Remove the original package section since esbuild will handle packaging
# package:
#   patterns:
#     - '!node_modules/.cache/**'
#     - '!.git/**'
#     - '!.github/**'
#     - '!tests/**'
#     - 'node_modules/**' # Include node_modules
#     - 'package-lock.json'

functions:
  api:
    name: 'izole-api'
    handler: main.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin  # Keep this if you were using it before

custom:
  dotenv:
    path: .env
    include:
      - MONGO_URI
      - SECRET_KEY
  
  # Add esbuild configuration
  esbuild:
    bundle: true
    minify: false  # Set to true in production for smaller packages
    sourcemap: false
    exclude:
      - aws-sdk  # AWS SDK is provided by Lambda
    target: 'node18'
    platform: 'node'
    concurrency: 10
    # If you have external modules that can't be bundled properly, list them here
    # external:
    #   - 'some-problematic-module'