name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'
      
      - name: Install dependencies
        run: |
          cd backend
          npm ci
          npm install --save-dev serverless-esbuild esbuild
      
      - name: Install Serverless Framework
        run: npm install -g serverless
      
      - name: Package and deploy with Serverless
        env:
          SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
          MONGO_URI: ${{secrets.MONGO_URI}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          NODE_OPTIONS: "--max-old-space-size=16384"
        run: |
          cd backend
          serverless deploy